# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 923b79914ce47e83152e99989436e60c611a2ee82dbb6664e3a70b89e5397f96e931f7078c67785f01666cd14b7aa574528b86b899ee4dbb3814b0fc9a674306

test:
  secret_key_base: f29c06c6f57bb2b1cac9eb459080f1f03640c998a48bfe63c137f6b5b1dbca381f8f68d4cbc255f9c02d66f3e72dc2a00c2b44a84f199074d51bdc71dba8414d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
